### ISSUE TITLE
Allow routes to be excluded

### ISSUE THREAD

**Issue by ttpham0111** [channelcat/sanic-openapi#21]
Is it possible to exclude some urls from the docs?

**Comment by raphaeldehoussefaktory** [comment]
+1
We have more "private" methods that we don't want to show in the swagger/openapi docs.
With others library, we just don't document the method and it doesn't appear, here, they're all included.

Thanks!

**Comment by raphaeldehoussefaktory** [comment]
PR https://github.com/channelcat/sanic-openapi/pull/20

**Comment by Typhon66** [comment]
PR is merged
