### ISSUE TITLE
@doc.produces & @doc.consumes not working

### ISSUE THREAD

**Issue by c-goosen** [channelcat/sanic-openapi#63]
Hi. 

Tried a couple of things and @doc.consumes & @doc.produces isn't working.

Could it be related to using sanic's blueprints?

Will try and have a look myself if I have some time. 

CG

**Comment by robertorobles** [comment]
+1

**Comment by c-goosen** [comment]
Think I was missing something so closing this for now. If I see something else I will rather open a issue again. Thanks
